# permissions for end users to view secretmappers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: secretmapper-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-testing
    app.kubernetes.io/part-of: operator-testing
    app.kubernetes.io/managed-by: kustomize
  name: secretmapper-viewer-role
rules:
- apiGroups:
  - theplatformteam.com
  resources:
  - secretmappers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - theplatformteam.com
  resources:
  - secretmappers/status
  verbs:
  - get
