apiVersion: theplatformteam.com/v1alpha1
kind: Secretmapper
metadata:
  labels:
    app.kubernetes.io/name: secretmapper
    app.kubernetes.io/instance: secretmapper-sample
    app.kubernetes.io/part-of: operator-testing
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: operator-testing
  name: secretmapper-sample
spec:
  source:
    namespace: namespace1
    name: mysecret
  destination:
    namespace: namespace2
    name: mycopiedsecret
